// zfs/src/components/disks/ReplaceDiskModal.vue
<template>
    <PfModal :isOpen="showFlag" title="Replace Disk" variant="large" @close="closeModal()">
            <div>
                <!-- Disk ID (Select) -->
                <div>
                    <label :for="getIdKey('disk-identifier')"
                        class="block text-sm font-medium leading-6 text-default">Disk Identifier</label>
                    <select :id="getIdKey('disk-identifier')" v-model="diskIdentifier" name="disk-identifier"
                        class="text-default bg-default mt-1 block w-full input-textlike sm:text-sm sm:leading-6">
                        <option value="sd_path">Block Device</option>
                        <option value="phy_path">Hardware Path</option>
                        <option value="vdev_path">Device Alias</option>
                    </select>
                </div>

                <!-- Disk selection, shows disks that are not in use -->
                <label :for="getIdKey('available-disk-list')"
                    class="my-1 block text-sm font-medium leading-6 text-default">Select Disks</label>
                <ul v-if="availableDisks.length > 0" :id="getIdKey('available-disk-list')" role="list"
                    class="flex flex-row flex-wrap gap-2">
                    <li v-for="(disk, diskIdx) in availableDisks" :key="diskIdx" class="my-2">
                        <button class="flex min-w-fit w-full h-full border border-default rounded-lg"
                            :title="disk.hasPartitions! ? 'Disk already has partitions. Proceed with caution.' : getDiskIDName(allDisks, diskIdentifier, disk.name!)"
                            :class="diskCardClass(disk.name)">
                            <label :for="getIdKey(`disk-${diskIdx}`)"
                                class="flex flex-col w-full py-4 mx-2 text-sm gap-0.5 justify-start">
                                <span class="flex flex-row flex-grow w-full justify-between">
                                    <input :id="getIdKey(`disk-${diskIdx}`)" type="checkbox" :value="disk.name"
                                        :name="`disk-${disk.name}`" :checked="selectedDisk === disk.name"
                                        @change="selectSingleDisk(disk.name)"
                                        class="justify-start w-4 h-4 text-success bg-well border-default rounded focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2" />
                                    <div v-if="disk.hasPartitions!"
                                        title="Disk already has partitions. Proceed with caution."
                                        class="flex items-center justify-center h-6 w-6 bg-default rounded-full ml-2">
                                        <ExclamationCircleIcon class="h-6 text-orange-700" />
                                    </div>
                                    <div v-if="disk.errors && disk.errors!.length > 0"
                                        title="This disk belongs to an exported pool. Force Add to override."
                                        class="flex items-center justify-center h-6 w-6 bg-default rounded-full ml-2">
                                        <ExclamationTriangleIcon class="h-6 text-danger" />
                                    </div>
                                </span>
                                <h3 class="truncate text-sm font-medium text-default">
                                    {{ truncateName((getDiskIDName(allDisks, diskIdentifier, disk.name!)), 8) }}</h3>
                                <p class="mt-1 truncate text-sm text-default">{{ disk.type }}</p>
                                <p class="mt-1 truncate text-sm text-default">Capacity: {{ disk.capacity }}</p>
                            </label>
                        </button>
                    </li>
                </ul>
                <div v-if="availableDisks.length == 0">
                    No Disks Available
                </div>

            </div>

        <template #footer>
            <div class="w-full grid grid-rows-2">
                <div class="w-full row-start-1 justify-center items-center">
                    <div class="justify-self-start mt-2">
                        <p class="text-danger" v-if="diskSizeFeedback">{{ diskSizeFeedback }}</p>
                        <p class="text-danger" v-if="diskBelongsFeedback">{{ diskBelongsFeedback }}</p>
                    </div>
                </div>

                <div class="button-group-row w-full justify-between row-start-2">
                    <div class="button-group-row mt-2 items-center">
                        <button @click="closeModal" :id="getIdKey('close-replace-disk-btn')"
                            name="close-replace-disk-btn" class="pf-v5-c-button pf-m-danger">Close</button>

                        <PfSwitch v-model="diskVDevPoolData.forceReplace"
                            :id="getIdKey('force-add-vdev')"
                            label="Forcefully Replace Disk" />
                    </div>
                    <div class="button-group-row mt-2">
                        <button v-if="!adding" id="replace-disk-btn"
                            class="pf-v5-c-button pf-m-primary"
                            @click="replaceDiskBtn">Replace Disk</button>
                        <button disabled v-if="adding" id="finish" type="button"
                            class="pf-v5-c-button pf-m-primary pf-m-in-progress">
                            Replacing...
                        </button>
                    </div>
                </div>
            </div>
        </template>
    </PfModal>
</template>
<script setup lang="ts">
import { ref, inject, Ref, computed, onMounted } from 'vue';
import PfModal from '../pf/PfModal.vue';
import PfSwitch from '../pf/PfSwitch.vue';
import { ExclamationCircleIcon, ExclamationTriangleIcon } from '@heroicons/vue/24/outline';
import { convertSizeToBytes, getDiskIDName, truncateName } from '../../composables/helpers';
import { replaceDisk } from '../../composables/disks';
import { loadImportablePools } from '../../composables/loadImportables';
import { ZPool, VDev, VDevDisk, ZFSFileSystemInfo, DiskIdentifier } from '@45drives/houston-common-lib';
import { pushNotification, Notification } from '@45drives/houston-common-ui';
import { PoolScanObjectGroup, PoolDiskStats, Activity } from '../../types';
import { useRefreshAllData } from '../../composables/useRefreshAllData';


interface ReplaceDiskModalProps {
    idKey: string;
    pool: ZPool;
    vDev: VDev;
    disk: VDevDisk;
    showFlag: boolean;
}

const props = defineProps<ReplaceDiskModalProps>();
const truncateText = inject<Ref<string>>('style-truncate-text')!;

const showFlag = ref(props.showFlag);

const emit = defineEmits(['close']);

const closeModal = () => {
    emit('close');
}

const showReplaceDiskModal = inject<Ref<boolean>>('show-replace-modal')!;
const selectedDisk = ref(''); // Holds the name of the selected disk

function selectSingleDisk(diskName) {
    // If the same disk is clicked again, deselect it; otherwise, select the new disk
    selectedDisk.value = selectedDisk.value === diskName ? '' : diskName;
}

const pools = inject<Ref<ZPool[]>>('pools')!;
const allDisks = inject<Ref<VDevDisk[]>>('disks')!;
const datasets = inject<Ref<ZFSFileSystemInfo[]>>('datasets')!;

const diskIdentifier = ref<DiskIdentifier>('vdev_path');
const diskSizeFeedback = ref('')

const phyPathPrefix = '/dev/disk/by-path/';
const sdPathPrefix = '/dev/';
const newDisk = ref();
const oldDisk = ref();
const diskNewName = ref('');
const diskNewPath = ref('');
const diskExistPath = ref('');
const diskExistName = ref('');
const diskBelongsFeedback = ref('');
const adding = ref(false);

const disksLoaded = inject<Ref<boolean>>('disks-loaded')!;
const poolsLoaded = inject<Ref<boolean>>('pools-loaded')!;
const fileSystemsLoaded = inject<Ref<boolean>>('datasets-loaded')!;
const scanObjectGroup = inject<Ref<PoolScanObjectGroup>>('scan-object-group')!;
const poolDiskStats = inject<Ref<PoolDiskStats>>('pool-disk-stats')!;

const scanActivities = inject<Ref<Map<string, Activity>>>('scan-activities')!;
const trimActivities = inject<Ref<Map<string, Activity>>>('trim-activities')!;

const availableDisks = computed<VDevDisk[]>(() => {
    return allDisks.value.filter(disk => disk.guid === "");
});

const diskVDevPoolData = ref({
    existingDiskName: '',
    newDiskName: '',
    vDevName: props.vDev.name,
    poolName: props.pool.name,
    forceReplace: false,
});

//change color of disk when selected
const diskCardClass = (diskName) => {
    return selectedDisk.value === diskName ? 'bg-green-300 dark:bg-green-700' : '';
};

function setDiskNamePath() {
    oldDisk.value = props.disk;
    // console.log('setting oldDisk.value:', oldDisk.value);
    // console.log('getting selectedDisk.value:', selectedDisk.value);
    newDisk.value = allDisks.value.find(disk => disk.name === selectedDisk.value);
    // console.log('setting newDisk.value:', newDisk.value);
    
    switch (diskIdentifier.value) {
        case 'vdev_path':
            diskNewPath.value = newDisk.value!.vdev_path;
            diskNewName.value = selectedDisk.value;
            diskExistPath.value = oldDisk.value!.path;
            diskExistName.value = oldDisk.value!.name;
            // console.log('diskNewPath:', diskNewPath.value, 'diskNewName:', diskNewName.value);
            // console.log('diskExistPath:', diskExistPath.value, 'diskExistName:', diskExistName.value);
            break;
        case 'phy_path':
            diskNewPath.value = newDisk.value!.phy_path;
             diskNewName.value = diskNewPath.value.replace(phyPathPrefix, '');
            diskExistPath.value = oldDisk.value!.path;
             diskExistName.value = diskExistPath.value.replace(phyPathPrefix, '');
            // console.log('diskNewPath:', diskNewPath.value, 'diskNewName:', diskNewName.value);
            // console.log('diskExistPath:', diskExistPath.value, 'diskExistName:', diskExistName.value);
            break;
        case 'sd_path':
            diskNewPath.value = newDisk.value!.sd_path;
             diskNewName.value = diskNewPath.value.replace(sdPathPrefix, '');
            diskExistPath.value = oldDisk.value!.path;
             diskExistName.value = diskExistPath.value.replace(sdPathPrefix, '');
            // console.log('diskNewPath:', diskNewPath.value, 'diskNewName:', diskNewName.value);
            // console.log('diskExistPath:', diskExistPath.value, 'diskExistName:', diskExistName.value);
            break;
        default:
            console.log('error with set diskName/paths');
            break;
    }
}


async function replaceDiskBtn() {
    if (diskSizeMatch()) {
        if (!diskBelongsToImportablePool() || diskVDevPoolData.value.forceReplace) {
            setDiskNamePath();
            diskVDevPoolData.value.newDiskName = diskNewName.value;
            diskVDevPoolData.value.existingDiskName = diskExistName.value;
            // console.log('all data of disk being replaceed:', diskVDevPoolData.value);
                
            adding.value = true;
            try {
                const output: any =  await replaceDisk(diskVDevPoolData.value.poolName, diskVDevPoolData.value.existingDiskName, diskVDevPoolData.value.newDiskName, diskVDevPoolData.value.forceReplace);

                if (output == null || output.error) {
				const errorMessage = output?.error || 'Unknown error';
                    adding.value = false;
                    pushNotification(new Notification('Replace Disk Failed', `There was an error replacing this disk: ${errorMessage}`, 'error', 5000));
                } else {
           
                    showReplaceDiskModal.value = false;
                    adding.value = false;
                    await refreshAllData();
                    pushNotification(new Notification('Disk Replaced', `Replaced disk successfully.`, 'success', 5000));
                }
            } catch (error) {
                console.error(error);
            }

        }
    }
}

const diskSizeMatch = () => {
    let result = true;
    diskSizeFeedback.value = '';
    // console.log("Checking disk:", selectedDisk.value);
    
    if (selectedDisk.value == '') {
        diskSizeFeedback.value = 'At least one disk is required.'
        return false;
    }

    const newDiskData = allDisks.value.find(fullDisk => fullDisk.name === selectedDisk.value);

    if (newDiskData) {
        // console.log('newDiskCapacity before conversion:', newDiskData!.capacity);
        const newCapacity = convertSizeToBytes(newDiskData!.capacity!);
        // console.log('newCapacity:', newCapacity);

        const oldDisks = props.vDev.disks;
        // console.log('oldDisks:', oldDisks);

        for (const oldDisk of oldDisks) {

            // console.log('currentCapacity before conversion:', oldDisk!.capacity, false);
            const currentCapacity = convertSizeToBytes(oldDisk.capacity!);
            // console.log('currentCapacity:', currentCapacity);

            if (newCapacity < currentCapacity) {
                diskSizeFeedback.value = "Cannot replace. Please select a disk that has capacity greater than or equal to current disks."
                result = false;
                break;
            }
        }
    }

    return result;
};

const importablePools = inject<Ref<ZPool[]>>('importable-pools')!;
const diskBelongsToImportablePool = () => {
	let result = false;
	diskBelongsFeedback.value = '';

	if (diskVDevPoolData.value.forceReplace) {
		return false;
	}
    const selectedNewDisk = allDisks.value.find(fullDisk => fullDisk.name == selectedDisk.value);
        // console.log('selectedDisk:', selectedDisk);
        importablePools.value.forEach(pool => {
            // console.log('importablePool:', pool);
            pool.vdevs.forEach(importableVDev => {
                // console.log('importableVDev:', importableVDev);
                importableVDev.disks.forEach(disk => {
                    // console.log('importableDisk:', disk);
                    if (selectedNewDisk!.name == disk.name) {
                        result = true;
                        diskBelongsFeedback.value = `This disk was used in exported pool '${pool.name}'.\n Use Force Add to override and use disk in new Vdev.`;
                        // console.log(`Disk belongs to importable pool: ${pool.name}`);
                    }
                });
            });
        });

	// console.log('diskBelongsFeedback:', diskBelongsFeedback.value);
	return result;
}

const { refreshAllData } = useRefreshAllData({
    poolData: pools,
    diskData: allDisks,
    filesystemData: datasets,
    disksLoaded,
    poolsLoaded,
    fileSystemsLoaded,
    scanObjectGroup,
    poolDiskStats,
    scanActivities,
    trimActivities
});

onMounted(() => {
	loadImportablePools(importablePools.value, allDisks, pools);
});

const getIdKey = (name: string) => `${props.idKey}-${name}`;
</script>

// zfs/src/components/disks/ReplaceDiskModal.tsx
import React, { useState, useMemo, useCallback } from 'react';
import {
  Modal,
  ModalVariant,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Form,
  FormGroup,
  FormSelect,
  FormSelectOption,
  Button,
  Switch,
  Alert,
  Gallery,
  GalleryItem,
  Card,
  CardBody,
  Flex,
  FlexItem,
  Icon,
  Content,
  Checkbox,
} from '@patternfly/react-core';
import {
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
} from '@patternfly/react-icons';
import type { VDevDisk } from '@45drives/houston-common-lib';
import { useZfsData } from '../../contexts/ZfsDataContext';
import { replaceDisk } from '../../hooks/useDiskOperations';
import { convertSizeToBytes } from '../../utils/formatters';
import { getDiskIDName, truncateName } from '../../utils/helpers';

type DiskIdentifier = 'sd_path' | 'phy_path' | 'vdev_path';

interface ReplaceDiskModalProps {
  isOpen: boolean;
  onClose: () => void;
  poolName: string;
  vdevName: string;
  vdevDisks: VDevDisk[];
  /** The specific disk being replaced. */
  disk: VDevDisk;
}

export const ReplaceDiskModal: React.FC<ReplaceDiskModalProps> = ({
  isOpen,
  onClose,
  poolName,
  vdevName,
  vdevDisks,
  disk: existingDisk,
}) => {
  const { disks, importablePools, refreshAll } = useZfsData();

  const [diskIdentifier, setDiskIdentifier] = useState<DiskIdentifier>('vdev_path');
  const [selectedDisk, setSelectedDisk] = useState('');
  const [forceReplace, setForceReplace] = useState(false);
  const [replacing, setReplacing] = useState(false);
  const [sizeFeedback, setSizeFeedback] = useState('');
  const [belongsFeedback, setBelongsFeedback] = useState('');

  const availableDisks = useMemo<VDevDisk[]>(
    () => disks.filter((d) => d.guid === ''),
    [disks],
  );

  const toggleDiskSelection = useCallback((diskName: string) => {
    setSelectedDisk((prev) => (prev === diskName ? '' : diskName));
    setSizeFeedback('');
    setBelongsFeedback('');
  }, []);

  const diskSizeMatch = useCallback((): boolean => {
    setSizeFeedback('');

    if (!selectedDisk) {
      setSizeFeedback('At least one disk is required.');
      return false;
    }

    const newDiskData = disks.find((d) => d.name === selectedDisk);
    if (!newDiskData) return false;

    const newCapacity = convertSizeToBytes(newDiskData.capacity ?? '0');

    for (const oldDisk of vdevDisks) {
      const currentCapacity = convertSizeToBytes(oldDisk.capacity ?? '0');
      if (newCapacity < currentCapacity) {
        setSizeFeedback(
          'Cannot replace. Please select a disk that has capacity greater than or equal to current disks.',
        );
        return false;
      }
    }

    return true;
  }, [disks, selectedDisk, vdevDisks]);

  const diskBelongsToImportablePool = useCallback((): boolean => {
    setBelongsFeedback('');

    if (forceReplace) return false;

    const selectedNewDisk = disks.find((d) => d.name === selectedDisk);
    if (!selectedNewDisk) return false;

    for (const pool of importablePools) {
      for (const vdev of pool.vdevs) {
        for (const d of vdev.disks) {
          if (selectedNewDisk.name === d.name) {
            setBelongsFeedback(
              `This disk was used in exported pool '${pool.name}'. Use Force Add to override and use disk in new Vdev.`,
            );
            return true;
          }
        }
      }
    }

    return false;
  }, [disks, forceReplace, importablePools, selectedDisk]);

  const resolveDiskNames = useCallback((): {
    existingDiskName: string;
    newDiskName: string;
  } => {
    const PHY_PREFIX = '/dev/disk/by-path/';
    const SD_PREFIX = '/dev/';

    const newDisk = disks.find((d) => d.name === selectedDisk);
    let existingDiskName = existingDisk.name ?? '';
    let newDiskName = selectedDisk;

    if (newDisk) {
      switch (diskIdentifier) {
        case 'vdev_path':
          newDiskName = selectedDisk;
          existingDiskName = existingDisk.name ?? '';
          break;
        case 'phy_path':
          newDiskName = (newDisk.phy_path ?? '').replace(PHY_PREFIX, '');
          existingDiskName = (existingDisk.path ?? '').replace(PHY_PREFIX, '');
          break;
        case 'sd_path':
          newDiskName = (newDisk.sd_path ?? '').replace(SD_PREFIX, '');
          existingDiskName = (existingDisk.path ?? '').replace(SD_PREFIX, '');
          break;
      }
    }

    return { existingDiskName, newDiskName };
  }, [diskIdentifier, disks, existingDisk, selectedDisk]);

  const handleReplace = useCallback(async () => {
    if (!diskSizeMatch()) return;
    if (diskBelongsToImportablePool() && !forceReplace) return;

    const { existingDiskName, newDiskName } = resolveDiskNames();

    setReplacing(true);
    try {
      const output: any = await replaceDisk(
        poolName,
        existingDiskName,
        newDiskName,
        forceReplace,
      );

      if (output == null || output.error) {
        const errorMessage = output?.error || 'Unknown error';
        setSizeFeedback(`Error replacing disk: ${errorMessage}`);
      } else {
        await refreshAll();
        onClose();
      }
    } catch (error) {
      console.error('Replace disk error:', error);
    } finally {
      setReplacing(false);
    }
  }, [
    diskBelongsToImportablePool,
    diskSizeMatch,
    forceReplace,
    onClose,
    poolName,
    refreshAll,
    resolveDiskNames,
  ]);

  return (
    <Modal
      variant={ModalVariant.large}
      isOpen={isOpen}
      onClose={onClose}
      aria-label="Replace Disk"
    >
      <ModalHeader title="Replace Disk" />
      <ModalBody>
        <Form>
          <FormGroup label="Disk Identifier" fieldId="replace-disk-identifier">
            <FormSelect
              id="replace-disk-identifier"
              value={diskIdentifier}
              onChange={(_event, val) => setDiskIdentifier(val as DiskIdentifier)}
            >
              <FormSelectOption value="sd_path" label="Block Device" />
              <FormSelectOption value="phy_path" label="Hardware Path" />
              <FormSelectOption value="vdev_path" label="Device Alias" />
            </FormSelect>
          </FormGroup>

          <FormGroup label="Select Replacement Disk" fieldId="replace-available-disks">
            {availableDisks.length === 0 ? (
              <Content component="p">No Disks Available</Content>
            ) : (
              <Gallery hasGutter minWidths={{ default: '160px' }}>
                {availableDisks.map((disk, idx) => {
                  const isSelected = selectedDisk === disk.name;
                  const displayName = truncateName(
                    getDiskIDName(disks, diskIdentifier, disk.name ?? ''),
                    8,
                  );

                  return (
                    <GalleryItem key={disk.name ?? idx}>
                      <Card
                        isSelectable
                        isSelected={isSelected}
                        onClick={() => toggleDiskSelection(disk.name ?? '')}
                        isCompact
                      >
                        <CardBody>
                          <Flex
                            justifyContent={{ default: 'justifyContentSpaceBetween' }}
                            alignItems={{ default: 'alignItemsCenter' }}
                          >
                            <FlexItem>
                              <Checkbox
                                id={`replace-disk-${idx}`}
                                isChecked={isSelected}
                                onChange={() => toggleDiskSelection(disk.name ?? '')}
                                label=""
                              />
                            </FlexItem>
                            <FlexItem>
                              {disk.hasPartitions && (
                                <Icon status="warning">
                                  <ExclamationCircleIcon title="Disk already has partitions. Proceed with caution." />
                                </Icon>
                              )}
                              {disk.errors && disk.errors.length > 0 && (
                                <Icon status="danger">
                                  <ExclamationTriangleIcon title="This disk belongs to an exported pool. Force Add to override." />
                                </Icon>
                              )}
                            </FlexItem>
                          </Flex>
                          <Content component="h3">{displayName}</Content>
                          <Content component="small">{disk.type}</Content>
                          <br />
                          <Content component="small">Capacity: {disk.capacity}</Content>
                        </CardBody>
                      </Card>
                    </GalleryItem>
                  );
                })}
              </Gallery>
            )}
          </FormGroup>
        </Form>
      </ModalBody>
      <ModalFooter>
        <Flex direction={{ default: 'column' }} style={{ width: '100%' }}>
          {sizeFeedback && (
            <FlexItem>
              <Alert variant="danger" isInline isPlain title={sizeFeedback} />
            </FlexItem>
          )}
          {belongsFeedback && (
            <FlexItem>
              <Alert variant="danger" isInline isPlain title={belongsFeedback} />
            </FlexItem>
          )}
          <FlexItem>
            <Flex
              justifyContent={{ default: 'justifyContentSpaceBetween' }}
              alignItems={{ default: 'alignItemsCenter' }}
            >
              <Flex alignItems={{ default: 'alignItemsCenter' }} spaceItems={{ default: 'spaceItemsMd' }}>
                <FlexItem>
                  <Button variant="danger" onClick={onClose}>
                    Close
                  </Button>
                </FlexItem>
                <FlexItem>
                  <Switch
                    id="replace-force-switch"
                    label="Forcefully Replace Disk"
                    isChecked={forceReplace}
                    onChange={(_event, checked) => setForceReplace(checked)}
                  />
                </FlexItem>
              </Flex>
              <FlexItem>
                <Button
                  variant="primary"
                  onClick={handleReplace}
                  isLoading={replacing}
                  isDisabled={replacing}
                >
                  {replacing ? 'Replacing...' : 'Replace Disk'}
                </Button>
              </FlexItem>
            </Flex>
          </FlexItem>
        </Flex>
      </ModalFooter>
    </Modal>
  );
};

export default ReplaceDiskModal;
